### ISSUE TITLE
I was a little confused by the naming of folders

### ISSUE THREAD

**Issue by steveriggins** [editorscut/ec011CombineKickstart#13]
When I got to Chapter 2, FarFarAway starts off with "Open the Forest project in 02/_StartHere" but the only "_StartHere" was at the top of the directory. Then I realized I was in "01/", which also has a folder named "02"

Not a bug nor issue, but just wanted to file feedback that I ran into this.

**Comment by axello** [comment]
Yeah, I had the same problem. Too many folders called 02 and _StartHere  :-)

**Comment by dimsumthinking** [comment]
Thanks - if it's something that I need to change, please let me know. At one time I had named them Chapter02 and Section02 but then the code headers were too long. I'll add a comment at the start of some chapters reminding you to switch folders. Thank you
