### ISSUE TITLE
Speling errors chapter 3

### ISSUE THREAD

**Issue by axello** [editorscut/ec011CombineKickstart#14]
I'm going to do things differently this chapter, as I have way to many issues open here in this repo. I'm going to put all the simple _speling_ errors in this one issue, and issues of a more contemplative nature in their own issue.

Page numbers are from file: CombineDrop4.pdf

I see several were already fixed in Combine Drop 6, but the issues below were not fixed yet

Annotation summary:

--- Page 79 ---

Highlight (red), Axel Roest:
get it's → get its

--- Page 120 ---

Highlight (red), Axel Roest:
easier that I thought → easier than I thought

--- Page 123 ---

Highlight (red), Axel Roest:
pubulisher

--- Page 133 ---

Highlight (yellow), Axel Roest:
that vends

* Does the publisher sell its goods, or does it give them away? I have the feeling that 'vendor' is a weird idiom here. At first I thought you meant to vent (an opinion or emotion)

Highlight (yellow), Axel Roest:
we look a powerful technique ... into small pieces while hiding

Perhaps a comma would be helpful here, before while?

--- Page 189 ---

Highlight (red), Axel Roest: (small)
They each indicate that a property is one for which → They each indicate that the (wrapped) property is one for which ?

**Comment by dimsumthinking** [comment]
all fixed. I think the comma before while is grammatically incorrect but clearer so I've done it

Thank you
