### ISSUE TITLE
So, why is Link.contents an optional at all?

### ISSUE THREAD

**Issue by axello** [editorscut/ec011CombineKickstart#16]
This is related to so many things, see below.

contents ultimately holds a string which is converted from a non-optional Int.
So this string conversion will ***always*** succeed, imho. Either that, or the string is "..."
Why is it an optional then?

Your argument that because UILabel _accepts_ an optional does not hold true, because I can very well write
label.text = "Daniel", where the latter is non-optional.

I've succesfully rewritten the code to use a non-optional contents and it works fine.

Or does this serve a purely educational purpose?

Cheers, Axel

--- Page 94 ---

Note (yellow), Axel Roest:
Why is it an optional? Because the Int is not an optional and conversion always succeeds?

--- Page 107 ---

Note (yellow), Axel Roest:
But WHY is contents an optional string anyway?
Won't it solve a lot of problems if this is always a string?

--- Page 121 ---

Highlight (red), Axel Roest:
In our case, we're supporting a UILabel so we need to produce a
String? not a String.

→ not in this use case

--- Page 125 ---

Highlight (yellow), Axel Roest:
We also want to serve UIKit so we need to be able to assign an Optional String as well. Create a second method named

assignDescription(asOptionalTo:) and add it to the extension.

**Comment by dimsumthinking** [comment]
I've tried to explain this in the text. You can do what you've done and an implicit conversion is happening. I'm being fussy about being explicit - also in more complicated cases (which you will quickly encounter) the compiler will not do this conversion and report a type mismatch. Your way works and my way is not needed - but I think I still prefer it. I appreciate you calling it out
