### ISSUE TITLE
importing Combine: elaborate

### ISSUE THREAD

**Issue by axello** [editorscut/ec011CombineKickstart#4]
drop 4, page 47

"It may surprise you that we've been able to use @Published and sink() without importing Combine."

Why don't you elaborate on that?

e.g.: Why Does it work in UIKit if you don't import swiftui?

**Comment by dimsumthinking** [comment]
Well TIL - thanks for this question. <var>Foundation</var> imports <var>Combine</var> and exposes the <var>@Published</var> property wrapper publicly using a typealias.

Added this as the explanation
